title: Xipeng Chen
url: "https://xipengchen.github.io/"
# baseurl: "/about"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "xipengchen.github.io"
footer_text: "&copy Xipeng Chen 2022. <code>Last updated: Jan, 2022<br/><br/></code>"

sass:
    style: compressed
    sass_dir: _sass

nav:
 # - name: "About"
 #  link: "/researcher/"
 - name: "About"
   link: "index"
 - name: "CV"
   link: "cv"
 - name: "Resource"
   link: "#"
 - name: "Code"
   link: "https://github.com/xipengchen"
 - name: "Contact"
   link: "contact"
